### ISSUE TITLE
Design new blended tracking process

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#48]
Blended development is an opt-in resource with its own workflow tracking process. Any engineering team in 2U can make use of this resource. This process needs to be fairly decentralized but provide insight into progress and outcomes.

- [ ] Plan for tracking progress on blended development projects
- [x] [Board for checking status](https://github.com/orgs/openedx/projects/21/views/1)
- [x] Wiki page describing process
- [ ] Get process approval from key stakeholders (Julie and Rhett?)
- [ ] Inform stakeholders (all eng managers?)

**Comment by natabene** [comment]
Current process described in [the Blended project readme](https://github.com/orgs/openedx/projects/21/views/1)

**Comment by nedbat** [comment]
tCRIL wouldn't make a new project for BD-14, wanted all tickets in public-engineering, so 2U is working in RacoonGang's work tracker.

**Comment by jristau1984** [comment]
https://github.com/openedx/tcril-engineering/issues/297 is the thread.

**Comment by natabene** [comment]
I have updated the Blended board readme with this [link](https://github.com/openedx/tcril-engineering/issues/297#issuecomment-1162331363) to describe how Blended 14 will be tracked. 
Can we close this issue now?

**Comment by nedbat** [comment]
Should we have this written in the wiki somewhere?

**Comment by nedbat** [comment]
This maybe subsumed by Public Workstreams.  We'll revisit once that is more fleshed out.

**Comment by nedbat** [comment]
@jristau1984 This still seems like it falls squarely in your court.  Can we move it forward? Or can you tell us why you don't think it's needed, or how this should be re-cast?  Public workstreams is a fine initiative, but seems larger than how to track blended work.

**Comment by jristau1984** [comment]
I think the question is whether we believe there should be visibility/tracking into Blended projects outside of the engineering manager that is driving the project forward. 

Example: I have methods for tracking BD-13, 14, and 38... but the 2U folks tracking BD-46 may have completely different mechanisms.  Do we need to have consistency in how we track them?  I'm not sure... 

Separately, I did update the Blended views a bit to make them a bit more targeted and consumable, but updating project field was a very manual task.

**Comment by nedbat** [comment]
I am happy to leave this per-manager for now.  If there should be shared practice, the engineering managers have mechanisms to talk collectively and agree.
